import { Component, ChangeDetectionStrategy } from '@angular/core';

// Subtle, consistent marker for "this came from AI" wherever an AI integration's result is
// shown alongside a local/fallback alternative (Quiz Duel, Quiz Game, Wordle, Jokes, Win Story,
// Timesheet analysis) -- deliberately tiny and low-opacity, and only ever shown for the AI case
// (the fallback case shows nothing, rather than cluttering every result with a "Local" label).
@Component({
  selector: 'app-ai-badge',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.Default,
  styles: [`
    .ai-badge { font-size: 0.7em; opacity: 0.4; margin-left: 4px; cursor: default; vertical-align: middle; }
  `],
  template: `<span class="ai-badge" title="Generated by AI">✨</span>`
})
export class AiBadgeComponent {}
