apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: team-manager

resources:
  - namespace.yaml
  - ../../base

images:
  - name: ghcr.io/juanlurie/team-manager-api
    newTag: "f374451ed90d97afc9f3b0df237e4d0ef77fd60a"
  - name: ghcr.io/juanlurie/team-manager-ui
    newTag: "f374451ed90d97afc9f3b0df237e4d0ef77fd60a"
  - name: ghcr.io/juanlurie/team-manager-mcp
    newTag: "f374451ed90d97afc9f3b0df237e4d0ef77fd60a"
