apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: team-manager

resources:
  - namespace.yaml
  - ../../base

images:
  - name: ghcr.io/juanlurie/team-manager-api
    newTag: "b07162b45d8de1d3a35f7e48899d3770379d3570"
  - name: ghcr.io/juanlurie/team-manager-ui
    newTag: "b07162b45d8de1d3a35f7e48899d3770379d3570"
  - name: ghcr.io/juanlurie/team-manager-mcp
    newTag: "b07162b45d8de1d3a35f7e48899d3770379d3570"
