// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TeamManager.Api.Infrastructure.Data;

#nullable disable

namespace TeamManager.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260423030000_AddAchievementPoints")]
    partial class AddAchievementPoints
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
