// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TeamManager.Api.Infrastructure.Data;

#nullable disable

namespace TeamManager.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526140000_AddCoffeeRunAdditions")]
    partial class AddCoffeeRunAdditions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.CoffeeRunMenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CoffeeRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<string?>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("MaxQuantity")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string?>("Sizes")
                        .HasColumnType("text");

                    b.Property<string?>("Additions")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoffeeRunId")
                        .HasDatabaseName("IX_CoffeeRunMenuItem_CoffeeRunId");

                    b.ToTable("CoffeeRunMenuItems");

                    b.HasOne("TeamManager.Api.Domain.Entities.CoffeeRun", "CoffeeRun")
                        .WithMany("MenuItems")
                        .HasForeignKey("CoffeeRunId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.CoffeeRunMenuTemplateItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<string?>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string?>("Sizes")
                        .HasColumnType("text");

                    b.Property<string?>("Additions")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("IX_CoffeeRunMenuTemplateItem_TemplateId");

                    b.ToTable("CoffeeRunMenuTemplateItems");

                    b.HasOne("TeamManager.Api.Domain.Entities.CoffeeRunMenuTemplate", "Template")
                        .WithMany("Items")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.CoffeeRunOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CoffeeRunOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoffeeRunMenuItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("numeric");

                    b.Property<string?>("SelectedSize")
                        .HasColumnType("text");

                    b.Property<string?>("SelectedAdditions")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoffeeRunMenuItemId")
                        .HasDatabaseName("IX_CoffeeRunOrderItem_CoffeeRunMenuItemId");

                    b.HasIndex("CoffeeRunOrderId")
                        .HasDatabaseName("IX_CoffeeRunOrderItem_CoffeeRunOrderId");

                    b.ToTable("CoffeeRunOrderItems");

                    b.HasOne("TeamManager.Api.Domain.Entities.CoffeeRunMenuItem", "MenuItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("CoffeeRunMenuItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TeamManager.Api.Domain.Entities.CoffeeRunOrder", "CoffeeRunOrder")
                        .WithMany("Items")
                        .HasForeignKey("CoffeeRunOrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
