// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TeamManager.Api.Infrastructure.Data;

#nullable disable

namespace TeamManager.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422110259_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.LeaveRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("DaysCount")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("SprintMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SprintMemberId");

                    b.ToTable("LeaveRecords");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.PI", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("PIs");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.Sprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsInnovationSprint")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("PIId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SprintNumber")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("PIId");

                    b.ToTable("Sprints");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.SprintMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamMemberId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamMemberId");

                    b.HasIndex("SprintId", "TeamMemberId")
                        .IsUnique();

                    b.ToTable("SprintMembers");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TeamLeadId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TeamLeadId");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.WorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("ActualPoints")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<DateOnly?>("CompletedDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal?>("EstimatedPoints")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<string>("ExternalTicketRef")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SprintMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SprintMemberId");

                    b.ToTable("WorkItems");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.LeaveRecord", b =>
                {
                    b.HasOne("TeamManager.Api.Domain.Entities.SprintMember", "SprintMember")
                        .WithMany("LeaveRecords")
                        .HasForeignKey("SprintMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SprintMember");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.Sprint", b =>
                {
                    b.HasOne("TeamManager.Api.Domain.Entities.PI", "PI")
                        .WithMany("Sprints")
                        .HasForeignKey("PIId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PI");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.SprintMember", b =>
                {
                    b.HasOne("TeamManager.Api.Domain.Entities.Sprint", "Sprint")
                        .WithMany("SprintMembers")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamManager.Api.Domain.Entities.TeamMember", "TeamMember")
                        .WithMany("SprintMemberships")
                        .HasForeignKey("TeamMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sprint");

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.TeamMember", b =>
                {
                    b.HasOne("TeamManager.Api.Domain.Entities.TeamMember", "TeamLead")
                        .WithMany("DirectReports")
                        .HasForeignKey("TeamLeadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TeamLead");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.WorkItem", b =>
                {
                    b.HasOne("TeamManager.Api.Domain.Entities.SprintMember", "SprintMember")
                        .WithMany("WorkItems")
                        .HasForeignKey("SprintMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SprintMember");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.PI", b =>
                {
                    b.Navigation("Sprints");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.Sprint", b =>
                {
                    b.Navigation("SprintMembers");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.SprintMember", b =>
                {
                    b.Navigation("LeaveRecords");

                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.TeamMember", b =>
                {
                    b.Navigation("DirectReports");

                    b.Navigation("SprintMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
