// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TeamManager.Api.Infrastructure.Data;

#nullable disable

namespace TeamManager.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526150000_AddScrumPokerTables")]
    partial class AddScrumPokerTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.ScrumPokerSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CreatedByMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string?>("StoryTitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string?>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Scale")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Revealed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevealedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ResetAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByMemberId")
                        .HasDatabaseName("IX_ScrumPokerSession_CreatedByMemberId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_ScrumPokerSession_CreatedAt");

                    b.ToTable("ScrumPokerSessions");

                    b.HasOne("TeamManager.Api.Domain.Entities.TeamMember", "CreatedByMember")
                        .WithMany()
                        .HasForeignKey("CreatedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByMember");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.ScrumPokerVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string?>("Value")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("VotedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("IX_ScrumPokerVote_MemberId");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_ScrumPokerVote_SessionId");

                    b.HasIndex(new[] { "SessionId", "MemberId" })
                        .IsUnique()
                        .HasDatabaseName("IX_ScrumPokerVote_SessionId_MemberId");

                    b.ToTable("ScrumPokerVotes");

                    b.HasOne("TeamManager.Api.Domain.Entities.ScrumPokerSession", "Session")
                        .WithMany("Votes")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TeamManager.Api.Domain.Entities.TeamMember", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Member");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.TeamMember", b =>
                {
                });
#pragma warning restore 612, 618
        }
    }
}
