// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TeamManager.Api.Infrastructure.Data;

#nullable disable

namespace TeamManager.Api.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260424120000_AddSprintGoal")]
partial class AddSprintGoal
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
    }
}
