// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TeamManager.Api.Infrastructure.Data;

#nullable disable

namespace TeamManager.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260423040000_AddPointAwards")]
    partial class AddPointAwards
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
