// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TeamManager.Api.Infrastructure.Data;

#nullable disable

namespace TeamManager.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506000000_AddDiscussionTasks")]
    partial class AddDiscussionTasks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
