// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TeamManager.Api.Infrastructure.Data;

#nullable disable

namespace TeamManager.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExternalSubjectId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.DiscussionPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("DiscussionPoints");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.DiscussionTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("DiscussionPointId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("TeamMemberId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DiscussionPointId");

                    b.HasIndex("TeamMemberId");

                    b.ToTable("DiscussionTasks");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.RetroAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SprintId");

                    b.ToTable("RetroActions");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.Feature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExternalTicketRef")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("SprintId");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.LeaveRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("DaysCount")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TeamMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TeamMemberId");

                    b.ToTable("LeaveRecords");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.PI", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("PIs");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.Sprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Goal")
                        .HasColumnType("text");

                    b.Property<string>("RetroWentWell")
                        .HasColumnType("text");

                    b.Property<string>("RetroDidntGoWell")
                        .HasColumnType("text");

                    b.Property<string>("RetroActionItems")
                        .HasColumnType("text");

                    b.Property<bool>("IsInnovationSprint")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("PIId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SprintNumber")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("PIId");

                    b.ToTable("Sprints");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.SprintMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamMemberId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamMemberId");

                    b.HasIndex("SprintId", "TeamMemberId")
                        .IsUnique();

                    b.ToTable("SprintMembers");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Crafts")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasDefaultValueSql("'[]'");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ExternalSubjectId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("JoinDate")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TeamLeadId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TeamLeadId");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.WorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("ActualPoints")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<DateOnly?>("CompletedDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal?>("EstimatedPoints")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<string>("ExternalTicketRef")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("FeatureId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("BlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BlockedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("SprintMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("SprintMemberId");

                    b.ToTable("WorkItems");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.Squad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Squads");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.SquadMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("SquadId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamMemberId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamMemberId");

                    b.HasIndex("SquadId", "TeamMemberId")
                        .IsUnique();

                    b.ToTable("SquadMembers");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.TimesheetEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("Billable")
                        .HasColumnType("boolean");

                    b.Property<int>("Hours")
                        .HasColumnType("integer");

                    b.Property<int>("Minutes")
                        .HasColumnType("integer");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Sentiment")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("TeamMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("TicketNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("WorkedFrom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("TeamMemberId", "Date");

                    b.ToTable("TimesheetEntries");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.RetroAction", b =>
                {
                    b.HasOne("TeamManager.Api.Domain.Entities.Sprint", null)
                        .WithMany()
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.TimesheetEntry", b =>
                {
                    b.HasOne("TeamManager.Api.Domain.Entities.TeamMember", "TeamMember")
                        .WithMany()
                        .HasForeignKey("TeamMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.Feature", b =>
                {
                    b.HasOne("TeamManager.Api.Domain.Entities.Sprint", "Sprint")
                        .WithMany("Features")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.LeaveRecord", b =>
                {
                    b.HasOne("TeamManager.Api.Domain.Entities.TeamMember", "TeamMember")
                        .WithMany("LeaveRecords")
                        .HasForeignKey("TeamMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.Sprint", b =>
                {
                    b.HasOne("TeamManager.Api.Domain.Entities.PI", "PI")
                        .WithMany("Sprints")
                        .HasForeignKey("PIId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PI");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.SprintMember", b =>
                {
                    b.HasOne("TeamManager.Api.Domain.Entities.Sprint", "Sprint")
                        .WithMany("SprintMembers")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamManager.Api.Domain.Entities.TeamMember", "TeamMember")
                        .WithMany("SprintMemberships")
                        .HasForeignKey("TeamMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sprint");

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.TeamMember", b =>
                {
                    b.HasOne("TeamManager.Api.Domain.Entities.TeamMember", "TeamLead")
                        .WithMany("DirectReports")
                        .HasForeignKey("TeamLeadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TeamLead");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.WorkItem", b =>
                {
                    b.HasOne("TeamManager.Api.Domain.Entities.Feature", "Feature")
                        .WithMany("WorkItems")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TeamManager.Api.Domain.Entities.SprintMember", "SprintMember")
                        .WithMany("WorkItems")
                        .HasForeignKey("SprintMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("SprintMember");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.Feature", b =>
                {
                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.PI", b =>
                {
                    b.Navigation("Sprints");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.Sprint", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("SprintMembers");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.SprintMember", b =>
                {
                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.SquadMember", b =>
                {
                    b.HasOne("TeamManager.Api.Domain.Entities.Squad", "Squad")
                        .WithMany("Members")
                        .HasForeignKey("SquadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamManager.Api.Domain.Entities.TeamMember", "TeamMember")
                        .WithMany("SquadMemberships")
                        .HasForeignKey("TeamMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Squad");
                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.Squad", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.TeamMember", b =>
                {
                    b.Navigation("DirectReports");

                    b.Navigation("LeaveRecords");

                    b.Navigation("SprintMemberships");

                    b.Navigation("SquadMemberships");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.Wheel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Wheels");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.WheelParticipant", b =>
                {
                    b.Property<Guid>("WheelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamMemberId")
                        .HasColumnType("uuid");

                    b.HasKey("WheelId", "TeamMemberId");

                    b.HasIndex("TeamMemberId");

                    b.ToTable("WheelParticipants");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.WheelParticipant", b =>
                {
                    b.HasOne("TeamManager.Api.Domain.Entities.TeamMember", "TeamMember")
                        .WithMany()
                        .HasForeignKey("TeamMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamManager.Api.Domain.Entities.Wheel", "Wheel")
                        .WithMany("Participants")
                        .HasForeignKey("WheelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamMember");
                    b.Navigation("Wheel");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.Wheel", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.MemberTimesheetConfig", b =>
                {
                    b.Property<Guid>("TeamMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExtraCategoriesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExtraProjectsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuickActionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TeamMemberId");

                    b.ToTable("MemberTimesheetConfigs");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.MemberPersonal", b =>
                {
                    b.Property<Guid>("TeamMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("PersonalMap")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TeamMemberId");

                    b.ToTable("MemberPersonals");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.MemberSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("TeamMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("TeamMemberId");

                    b.ToTable("MemberSkills");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.MemberSkillRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("MemberSkillId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateOnly>("RatedAt")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("MemberSkillId");

                    b.ToTable("MemberSkillRatings");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.MemberNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("TeamMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TeamMemberId");

                    b.ToTable("MemberNotes");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.MemberTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("TeamMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TeamMemberId");

                    b.ToTable("MemberTasks");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.SprintVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VoterSprintMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NomineeSprintMemberId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NomineeSprintMemberId");

                    b.HasIndex("SprintId", "VoterSprintMemberId")
                        .IsUnique();

                    b.ToTable("SprintVotes");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.MemberTimesheetConfig", b =>
                {
                    b.HasOne("TeamManager.Api.Domain.Entities.TeamMember", "TeamMember")
                        .WithOne()
                        .HasForeignKey("TeamManager.Api.Domain.Entities.MemberTimesheetConfig", "TeamMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.MemberPersonal", b =>
                {
                    b.HasOne("TeamManager.Api.Domain.Entities.TeamMember", "TeamMember")
                        .WithOne()
                        .HasForeignKey("TeamManager.Api.Domain.Entities.MemberPersonal", "TeamMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.MemberSkill", b =>
                {
                    b.HasOne("TeamManager.Api.Domain.Entities.TeamMember", "TeamMember")
                        .WithMany()
                        .HasForeignKey("TeamMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasMany("TeamManager.Api.Domain.Entities.MemberSkillRating", "Ratings")
                        .WithOne("MemberSkill")
                        .HasForeignKey("MemberSkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamMember");
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.MemberSkillRating", b =>
                {
                    b.Navigation("MemberSkill");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.MemberNote", b =>
                {
                    b.HasOne("TeamManager.Api.Domain.Entities.TeamMember", "TeamMember")
                        .WithMany()
                        .HasForeignKey("TeamMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.MemberTask", b =>
                {
                    b.HasOne("TeamManager.Api.Domain.Entities.TeamMember", "TeamMember")
                        .WithMany()
                        .HasForeignKey("TeamMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("TeamManager.Api.Domain.Entities.SprintVote", b =>
                {
                    b.HasOne("TeamManager.Api.Domain.Entities.Sprint", "Sprint")
                        .WithMany()
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamManager.Api.Domain.Entities.SprintMember", "Voter")
                        .WithMany()
                        .HasForeignKey("VoterSprintMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TeamManager.Api.Domain.Entities.SprintMember", "Nominee")
                        .WithMany()
                        .HasForeignKey("NomineeSprintMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sprint");
                    b.Navigation("Voter");
                    b.Navigation("Nominee");
                });
modelBuilder.Entity("TeamManager.Api.Domain.Entities.DiscussionTask", b =>                {                    b.HasOne("TeamManager.Api.Domain.Entities.DiscussionPoint", "DiscussionPoint")                        .WithMany()                        .HasForeignKey("DiscussionPointId")                        .OnDelete(DeleteBehavior.Cascade)                        .IsRequired();                    b.HasOne("TeamManager.Api.Domain.Entities.TeamMember", "Assignee")                        .WithMany()                        .HasForeignKey("TeamMemberId")                        .OnDelete(DeleteBehavior.SetNull);                    b.Navigation("DiscussionPoint");                    b.Navigation("Assignee");                });
#pragma warning restore 612, 618
        }
    }
}
