apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: team-manager
spec:
  selector:
    app: ui
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: team-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: ghcr.io/juanlurie/team-manager-ui:d055085d9f7462d4536c2f8ea01b7341f4adba6f
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
