apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: team-manager-beta

resources:
  - namespace.yaml
  - ../../base

images:
  - name: ghcr.io/juanlurie/team-manager-api
    newTag: "f640bf9d08b5b45182609506d89d0e1cdbbc4008"
  - name: ghcr.io/juanlurie/team-manager-ui
    newTag: "f640bf9d08b5b45182609506d89d0e1cdbbc4008"
  - name: ghcr.io/juanlurie/team-manager-mcp
    newTag: "f640bf9d08b5b45182609506d89d0e1cdbbc4008"
