apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: team-manager-beta

resources:
  - namespace.yaml
  - ../../base

images:
  - name: ghcr.io/juanlurie/team-manager-api
    newTag: "5d6b518651404df80320a5f8a9761f5dbbe0bba2"
  - name: ghcr.io/juanlurie/team-manager-ui
    newTag: "5d6b518651404df80320a5f8a9761f5dbbe0bba2"
  - name: ghcr.io/juanlurie/team-manager-mcp
    newTag: "5d6b518651404df80320a5f8a9761f5dbbe0bba2"
