apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: team-manager-beta

resources:
  - namespace.yaml
  - ../../base

images:
  - name: ghcr.io/juanlurie/team-manager-api
    newTag: "171bf00066c638288f296f48f26aae2a864c0cad"
  - name: ghcr.io/juanlurie/team-manager-ui
    newTag: "171bf00066c638288f296f48f26aae2a864c0cad"
  - name: ghcr.io/juanlurie/team-manager-mcp
    newTag: "171bf00066c638288f296f48f26aae2a864c0cad"
