import { Injectable } from '@angular/core';
import {
  SearchCapability,
  TuiScreen,
  TuiKeyBinding,
  McpDomain,
  FeatureCard,
} from '../models/showcase.model';

@Injectable({ providedIn: 'root' })
export class ShowcaseDataService {
  getSearchCapabilities(): SearchCapability[] {
    return [
      {
        name: 'Quick Open',
        icon: 'find_in_page',
        trigger: 'Ctrl+P / Cmd+P',
        description: 'Instantly navigate to any page or team member across the entire application. Opens a command-palette style search bar where you can type to filter results in real-time.',
        features: ['All 13+ pages indexed', 'Active team members included', 'Keyboard navigation with arrow keys', 'Enter to select, Escape to close'],
        details: 'Command-palette style navigation',
      },
      {
        name: 'K-Picker',
        icon: 'group_add',
        trigger: 'Ctrl+K / Cmd+K',
        description: 'Quickly search and select team members from anywhere in the app. Supports fuzzy matching so you can type partial names or initials to find the right person fast.',
        features: ['Fuzzy name matching', 'Filter by squad or team lead', 'Remembers recent selections', 'Single or multi-select mode'],
        details: 'Used across all forms and filter bars',
      },
      {
        name: 'Filter Bar',
        icon: 'filter_list',
        trigger: 'Inline',
        description: 'Powerful column-based filtering on data tables throughout the app. Type to search within any column, use @ mentions for assignee names, and clear all filters with a single Escape key.',
        features: ['Status, assignee, and squad filters', '@mention support for quick name lookup', 'Clear all filters with Escape', 'Real-time results as you type'],
        details: 'Available on dashboard and list views',
      },
      {
        name: 'Searchable Selects',
        icon: 'search',
        trigger: 'Dropdown',
        description: 'Every dropdown in the app is searchable. Instead of scrolling through long lists, simply start typing to find the option you need. Supports both single and multi-select with visual chips.',
        features: ['Single-select with live search', 'Multi-select with removable chips', 'Fuzzy matching for partial inputs', 'Used in forms and meeting availability'],
        details: 'Used in feature forms, sprint member selection, and meeting availability',
      },
    ];
  }

  getTuiScreens(): TuiScreen[] {
    return [
      { name: 'Dashboard', file: 'tui/screens/dashboard.py', description: 'Sprint overview: features, blockers, leave, unallocated members', icon: 'dashboard' },
      { name: 'Feature Detail', file: 'tui/screens/feature_detail.py', description: 'Work items by status tabs: Planned, InProgress, Blocked, Done', icon: 'list_alt' },
      { name: 'Work Items', file: 'tui/screens/work_items.py', description: "Member's work items grouped by status", icon: 'assignment' },
      { name: 'Add Feature', file: 'tui/screens/add_feature.py', description: 'Modal dialog to create new feature', icon: 'add_circle' },
    ];
  }

  getTuiKeyBindings(): TuiKeyBinding[] {
    return [
      { key: '[ / ]', macKey: '[ / ]', action: 'Navigate between sprints' },
      { key: 'n', macKey: 'n', action: 'Add new feature' },
      { key: 'Enter', macKey: 'Return', action: 'Open feature detail / work items' },
      { key: 'r', macKey: 'r', action: 'Refresh data' },
      { key: 'b / Esc', macKey: 'b / Esc', action: 'Go back' },
      { key: 'q', macKey: 'q', action: 'Quit' },
    ];
  }

  getTuiApiEndpoints(): string[] {
    return [
      'GET /api/v1/sprints',
      'GET /api/v1/dashboard/sprint/{id}',
      'GET /api/v1/dashboard/sprint/{id}/blockers',
      'GET /api/v1/dashboard/sprint/{id}/leave-summary',
      'GET /api/v1/sprint-members/{id}/work-items',
      'POST /api/v1/sprints/{id}/features',
    ];
  }

  getMcpDomains(): McpDomain[] {
    return [
      {
        name: 'Planning',
        icon: 'calendar_today',
        toolCount: 24,
        tools: [
          { name: 'list_pis', description: 'List all Program Increments', requiredParams: [], apiEndpoint: '/api/v1/pis', httpMethod: 'GET' },
          { name: 'get_pi', description: 'Get a single PI by ID', requiredParams: ['pi_id'], apiEndpoint: '/api/v1/pis/{id}', httpMethod: 'GET' },
          { name: 'create_pi', description: 'Create a new PI', requiredParams: ['name', 'start_date', 'end_date'], apiEndpoint: '/api/v1/pis', httpMethod: 'POST' },
          { name: 'update_pi', description: 'Update an existing PI', requiredParams: ['pi_id'], apiEndpoint: '/api/v1/pis/{id}', httpMethod: 'PUT' },
          { name: 'delete_pi', description: 'Delete a PI', requiredParams: ['pi_id'], apiEndpoint: '/api/v1/pis/{id}', httpMethod: 'DELETE' },
          { name: 'list_sprints', description: 'List sprints, optionally filtered', requiredParams: [], apiEndpoint: '/api/v1/sprints', httpMethod: 'GET' },
          { name: 'get_sprint', description: 'Get a sprint by ID', requiredParams: ['sprint_id'], apiEndpoint: '/api/v1/sprints/{id}', httpMethod: 'GET' },
          { name: 'create_sprint', description: 'Create a new sprint', requiredParams: ['name', 'start_date', 'end_date'], apiEndpoint: '/api/v1/sprints', httpMethod: 'POST' },
          { name: 'update_sprint', description: 'Update an existing sprint', requiredParams: ['sprint_id'], apiEndpoint: '/api/v1/sprints/{id}', httpMethod: 'PUT' },
          { name: 'delete_sprint', description: 'Delete a sprint', requiredParams: ['sprint_id'], apiEndpoint: '/api/v1/sprints/{id}', httpMethod: 'DELETE' },
          { name: 'close_sprint', description: 'Close (complete) a sprint', requiredParams: ['sprint_id'], apiEndpoint: '/api/v1/sprints/{id}/close', httpMethod: 'PATCH' },
          { name: 'clone_sprint', description: 'Clone a sprint with new dates', requiredParams: ['sprint_id'], apiEndpoint: '/api/v1/sprints/{id}/clone', httpMethod: 'POST' },
          { name: 'initialize_sprint_members', description: 'Initialize members for a sprint', requiredParams: ['sprint_id'], apiEndpoint: '/api/v1/sprints/{id}/initialize-members', httpMethod: 'POST' },
          { name: 'update_sprint_retro', description: 'Update retro data for a sprint', requiredParams: ['sprint_id'], apiEndpoint: '/api/v1/sprints/{id}/retro', httpMethod: 'PATCH' },
          { name: 'get_sprint_velocity', description: 'Get velocity data across sprints', requiredParams: [], apiEndpoint: '/api/v1/sprints/velocity', httpMethod: 'GET' },
          { name: 'list_sprint_features', description: 'List features for a sprint', requiredParams: ['sprint_id'], apiEndpoint: '/api/v1/sprints/{id}/features', httpMethod: 'GET' },
          { name: 'create_sprint_feature', description: 'Create a feature for a sprint', requiredParams: ['sprint_id', 'title'], apiEndpoint: '/api/v1/sprints/{id}/features', httpMethod: 'POST' },
          { name: 'update_sprint_feature', description: 'Update a sprint feature', requiredParams: ['sprint_id', 'feature_id'], apiEndpoint: '/api/v1/sprints/{id}/features/{fid}', httpMethod: 'PUT' },
          { name: 'delete_sprint_feature', description: 'Delete a sprint feature', requiredParams: ['sprint_id', 'feature_id'], apiEndpoint: '/api/v1/sprints/{id}/features/{fid}', httpMethod: 'DELETE' },
          { name: 'toggle_feature_active', description: 'Toggle feature active status', requiredParams: ['sprint_id', 'feature_id'], apiEndpoint: '/api/v1/sprints/{id}/features/{fid}/toggle-active', httpMethod: 'PATCH' },
          { name: 'list_all_features', description: 'List all features across sprints', requiredParams: [], apiEndpoint: '/api/v1/features', httpMethod: 'GET' },
          { name: 'set_feature_status', description: 'Set the status of a feature', requiredParams: ['feature_id', 'status'], apiEndpoint: '/api/v1/features/{id}/status', httpMethod: 'PATCH' },
          { name: 'list_work_items', description: 'List work items for a sprint member', requiredParams: ['sprint_member_id'], apiEndpoint: '/api/v1/sprint-members/{id}/work-items', httpMethod: 'GET' },
          { name: 'create_work_item', description: 'Create a work item', requiredParams: ['sprint_member_id', 'title', 'type', 'status'], apiEndpoint: '/api/v1/sprint-members/{id}/work-items', httpMethod: 'POST' },
          { name: 'get_work_item', description: 'Get a work item by ID', requiredParams: ['work_item_id'], apiEndpoint: '/api/v1/work-items/{id}', httpMethod: 'GET' },
          { name: 'update_work_item', description: 'Update a work item', requiredParams: ['work_item_id'], apiEndpoint: '/api/v1/work-items/{id}', httpMethod: 'PUT' },
          { name: 'update_work_item_status', description: 'Update work item status', requiredParams: ['work_item_id', 'status'], apiEndpoint: '/api/v1/work-items/{id}/status', httpMethod: 'PATCH' },
          { name: 'carry_over_work_item', description: 'Carry over work item to next sprint', requiredParams: ['work_item_id'], apiEndpoint: '/api/v1/work-items/{id}/carry-over', httpMethod: 'POST' },
          { name: 'delete_work_item', description: 'Delete a work item', requiredParams: ['work_item_id'], apiEndpoint: '/api/v1/work-items/{id}', httpMethod: 'DELETE' },
          { name: 'get_sprint_votes', description: 'Get votes for a sprint', requiredParams: ['sprint_id'], apiEndpoint: '/api/v1/sprints/{id}/votes', httpMethod: 'GET' },
          { name: 'cast_sprint_vote', description: 'Cast a vote in a sprint', requiredParams: ['sprint_id', 'target_id'], apiEndpoint: '/api/v1/sprints/{id}/votes', httpMethod: 'POST' },
          { name: 'award_sprint_mvp', description: 'Award MVP for a sprint', requiredParams: ['sprint_id', 'member_id'], apiEndpoint: '/api/v1/sprints/{id}/votes/award-mvp', httpMethod: 'POST' },
          { name: 'list_retro_actions', description: 'List retro actions', requiredParams: [], apiEndpoint: '/api/v1/retro-actions', httpMethod: 'GET' },
          { name: 'create_retro_action', description: 'Create a retro action', requiredParams: ['sprint_id', 'title'], apiEndpoint: '/api/v1/retro-actions', httpMethod: 'POST' },
          { name: 'update_retro_action', description: 'Update a retro action', requiredParams: ['retro_action_id'], apiEndpoint: '/api/v1/retro-actions/{id}', httpMethod: 'PUT' },
          { name: 'delete_retro_action', description: 'Delete a retro action', requiredParams: ['retro_action_id'], apiEndpoint: '/api/v1/retro-actions/{id}', httpMethod: 'DELETE' },
        ],
      },
      {
        name: 'Team',
        icon: 'people',
        toolCount: 12,
        tools: [
          { name: 'list_team_members', description: 'List team members', requiredParams: [], apiEndpoint: '/api/v1/team-members', httpMethod: 'GET' },
          { name: 'get_team_member', description: 'Get a team member by ID', requiredParams: ['member_id'], apiEndpoint: '/api/v1/team-members/{id}', httpMethod: 'GET' },
          { name: 'create_team_member', description: 'Add a new team member', requiredParams: ['first_name', 'last_name', 'email', 'role'], apiEndpoint: '/api/v1/team-members', httpMethod: 'POST' },
          { name: 'update_team_member', description: 'Update an existing team member', requiredParams: ['member_id'], apiEndpoint: '/api/v1/team-members/{id}', httpMethod: 'PUT' },
          { name: 'delete_team_member', description: 'Delete a team member', requiredParams: ['member_id'], apiEndpoint: '/api/v1/team-members/{id}', httpMethod: 'DELETE' },
          { name: 'list_squads', description: 'List all squads', requiredParams: [], apiEndpoint: '/api/v1/squads', httpMethod: 'GET' },
          { name: 'get_squad', description: 'Get a squad by ID', requiredParams: ['squad_id'], apiEndpoint: '/api/v1/squads/{id}', httpMethod: 'GET' },
          { name: 'create_squad', description: 'Create a new squad', requiredParams: ['name'], apiEndpoint: '/api/v1/squads', httpMethod: 'POST' },
          { name: 'update_squad', description: 'Update a squad', requiredParams: ['squad_id'], apiEndpoint: '/api/v1/squads/{id}', httpMethod: 'PUT' },
          { name: 'delete_squad', description: 'Delete a squad', requiredParams: ['squad_id'], apiEndpoint: '/api/v1/squads/{id}', httpMethod: 'DELETE' },
          { name: 'set_squad_members', description: 'Set all members of a squad', requiredParams: ['squad_id', 'member_ids'], apiEndpoint: '/api/v1/squads/{id}/members', httpMethod: 'PUT' },
          { name: 'set_member_squads', description: 'Set all squads a member belongs to', requiredParams: ['member_id', 'squad_ids'], apiEndpoint: '/api/v1/team-members/{id}/squads', httpMethod: 'PUT' },
        ],
      },
      {
        name: 'Meetings',
        icon: 'event',
        toolCount: 35,
        tools: [
          { name: 'list_meeting_series', description: 'List all meeting series', requiredParams: [], apiEndpoint: '/api/v1/meeting-series', httpMethod: 'GET' },
          { name: 'get_meeting_series', description: 'Get a meeting series by ID', requiredParams: ['series_id'], apiEndpoint: '/api/v1/meeting-series/{id}', httpMethod: 'GET' },
          { name: 'create_meeting_series', description: 'Create a meeting series', requiredParams: ['name'], apiEndpoint: '/api/v1/meeting-series', httpMethod: 'POST' },
          { name: 'update_meeting_series', description: 'Update a meeting series', requiredParams: ['series_id'], apiEndpoint: '/api/v1/meeting-series/{id}', httpMethod: 'PUT' },
          { name: 'delete_meeting_series', description: 'Delete a meeting series', requiredParams: ['series_id'], apiEndpoint: '/api/v1/meeting-series/{id}', httpMethod: 'DELETE' },
          { name: 'get_meeting_series_slots', description: 'Get slots for a meeting series', requiredParams: ['series_id'], apiEndpoint: '/api/v1/meeting-series/{id}/slots', httpMethod: 'GET' },
          { name: 'create_meeting_series_slots', description: 'Create slots for a meeting series', requiredParams: ['series_id', 'slots'], apiEndpoint: '/api/v1/meeting-series/{id}/slots', httpMethod: 'POST' },
          { name: 'update_meeting_series_slot', description: 'Update a slot in a meeting series', requiredParams: ['series_id', 'slot_id'], apiEndpoint: '/api/v1/meeting-series/{id}/slots/{sid}', httpMethod: 'PUT' },
          { name: 'delete_meeting_series_slot', description: 'Delete a slot from a meeting series', requiredParams: ['series_id', 'slot_id'], apiEndpoint: '/api/v1/meeting-series/{id}/slots/{sid}', httpMethod: 'DELETE' },
          { name: 'get_meeting_series_items', description: 'Get items for a meeting series', requiredParams: ['series_id'], apiEndpoint: '/api/v1/meeting-series/{id}/items', httpMethod: 'GET' },
          { name: 'create_meeting_series_item', description: 'Create an item for a meeting series', requiredParams: ['series_id', 'title'], apiEndpoint: '/api/v1/meeting-series/{id}/items', httpMethod: 'POST' },
          { name: 'update_meeting_series_item', description: 'Update an item in a meeting series', requiredParams: ['series_id', 'item_id'], apiEndpoint: '/api/v1/meeting-series/{id}/items/{iid}', httpMethod: 'PUT' },
          { name: 'delete_meeting_series_item', description: 'Delete an item from a meeting series', requiredParams: ['series_id', 'item_id'], apiEndpoint: '/api/v1/meeting-series/{id}/items/{iid}', httpMethod: 'DELETE' },
          { name: 'unconfirm_meeting_item', description: 'Unconfirm a meeting item', requiredParams: ['item_id'], apiEndpoint: '/api/v1/meeting-series/items/{iid}/unconfirm', httpMethod: 'POST' },
          { name: 'get_my_meeting_series', description: 'Get meeting series I am part of', requiredParams: [], apiEndpoint: '/api/v1/meeting-series/my-series', httpMethod: 'GET' },
          { name: 'get_my_meetings', description: 'Get my upcoming meetings', requiredParams: [], apiEndpoint: '/api/v1/meeting-series/my-meetings', httpMethod: 'GET' },
          { name: 'get_item_availability', description: 'Get availability for a meeting item', requiredParams: ['item_id'], apiEndpoint: '/api/v1/meeting-series/items/{iid}/availability', httpMethod: 'GET' },
          { name: 'add_item_availability', description: 'Add your availability for a meeting item', requiredParams: ['item_id', 'slot_ids'], apiEndpoint: '/api/v1/meeting-series/items/{iid}/availability', httpMethod: 'POST' },
          { name: 'remove_item_availability', description: 'Remove your availability for a meeting item', requiredParams: ['item_id', 'availability_id'], apiEndpoint: '/api/v1/meeting-series/items/{iid}/availability/{aid}', httpMethod: 'DELETE' },
          { name: 'get_bulk_availability', description: 'Get bulk availability for a meeting series', requiredParams: ['series_id'], apiEndpoint: '/api/v1/meeting-series/{id}/bulk-availability', httpMethod: 'GET' },
          { name: 'submit_bulk_availability', description: 'Submit bulk availability for a meeting series', requiredParams: ['series_id', 'availability'], apiEndpoint: '/api/v1/meeting-series/{id}/bulk-availability', httpMethod: 'POST' },
          { name: 'get_my_availability', description: 'Get my availability for a meeting series', requiredParams: ['series_id'], apiEndpoint: '/api/v1/meeting-series/{id}/my-availability', httpMethod: 'GET' },
          { name: 'set_my_availability', description: 'Set my availability for a meeting series', requiredParams: ['series_id', 'slot_ids'], apiEndpoint: '/api/v1/meeting-series/{id}/my-availability', httpMethod: 'POST' },
          { name: 'list_meeting_sessions', description: 'List all meeting sessions', requiredParams: [], apiEndpoint: '/api/v1/meeting-sessions', httpMethod: 'GET' },
          { name: 'get_meeting_session', description: 'Get a meeting session by ID', requiredParams: ['session_id'], apiEndpoint: '/api/v1/meeting-sessions/{id}', httpMethod: 'GET' },
          { name: 'create_meeting_session', description: 'Create a meeting session', requiredParams: ['name', 'date'], apiEndpoint: '/api/v1/meeting-sessions', httpMethod: 'POST' },
          { name: 'update_meeting_session', description: 'Update a meeting session', requiredParams: ['session_id'], apiEndpoint: '/api/v1/meeting-sessions/{id}', httpMethod: 'PUT' },
          { name: 'delete_meeting_session', description: 'Delete a meeting session', requiredParams: ['session_id'], apiEndpoint: '/api/v1/meeting-sessions/{id}', httpMethod: 'DELETE' },
          { name: 'update_meeting_session_status', description: 'Update the status of a meeting session', requiredParams: ['session_id', 'status'], apiEndpoint: '/api/v1/meeting-sessions/{id}/status', httpMethod: 'PATCH' },
          { name: 'book_meeting_slot', description: 'Book a slot in a meeting session', requiredParams: ['session_id', 'slot_id'], apiEndpoint: '/api/v1/meeting-sessions/{id}/slots/{sid}/book', httpMethod: 'POST' },
          { name: 'unbook_meeting_slot', description: 'Unbook a slot in a meeting session', requiredParams: ['session_id', 'slot_id'], apiEndpoint: '/api/v1/meeting-sessions/{id}/slots/{sid}/book', httpMethod: 'DELETE' },
          { name: 'list_session_types', description: 'List all session types', requiredParams: [], apiEndpoint: '/api/v1/session-types', httpMethod: 'GET' },
          { name: 'create_session_type', description: 'Create a session type', requiredParams: ['name'], apiEndpoint: '/api/v1/session-types', httpMethod: 'POST' },
          { name: 'list_slot_locations', description: 'List all slot locations', requiredParams: [], apiEndpoint: '/api/v1/slot-locations', httpMethod: 'GET' },
          { name: 'create_slot_location', description: 'Create a slot location', requiredParams: ['name'], apiEndpoint: '/api/v1/slot-locations', httpMethod: 'POST' },
        ],
      },
      {
        name: 'Personal',
        icon: 'person',
        toolCount: 14,
        tools: [
          { name: 'get_member_personal', description: 'Get personal info for a team member', requiredParams: ['member_id'], apiEndpoint: '/api/v1/team-members/{id}/personal', httpMethod: 'GET' },
          { name: 'update_member_personal', description: 'Update personal info for a team member', requiredParams: ['member_id', 'personal_info'], apiEndpoint: '/api/v1/team-members/{id}/personal', httpMethod: 'PUT' },
          { name: 'get_member_skills', description: 'Get skills for a team member', requiredParams: ['member_id'], apiEndpoint: '/api/v1/team-members/{id}/skills', httpMethod: 'GET' },
          { name: 'create_member_skill', description: 'Add a skill to a team member', requiredParams: ['member_id', 'skill_name'], apiEndpoint: '/api/v1/team-members/{id}/skills', httpMethod: 'POST' },
          { name: 'add_skill_rating', description: 'Add a rating to a member skill', requiredParams: ['member_id', 'skill_id', 'rating'], apiEndpoint: '/api/v1/team-members/{id}/skills/{sid}/ratings', httpMethod: 'POST' },
          { name: 'delete_member_skill', description: 'Delete a skill from a team member', requiredParams: ['member_id', 'skill_id'], apiEndpoint: '/api/v1/team-members/{id}/skills/{sid}', httpMethod: 'DELETE' },
          { name: 'get_member_notes', description: 'Get notes for a team member', requiredParams: ['member_id'], apiEndpoint: '/api/v1/team-members/{id}/notes', httpMethod: 'GET' },
          { name: 'create_member_note', description: 'Create a note for a team member', requiredParams: ['member_id', 'content'], apiEndpoint: '/api/v1/team-members/{id}/notes', httpMethod: 'POST' },
          { name: 'delete_member_note', description: 'Delete a note for a team member', requiredParams: ['member_id', 'note_id'], apiEndpoint: '/api/v1/team-members/{id}/notes/{nid}', httpMethod: 'DELETE' },
          { name: 'get_member_tasks', description: 'Get tasks for a team member', requiredParams: ['member_id'], apiEndpoint: '/api/v1/team-members/{id}/tasks', httpMethod: 'GET' },
          { name: 'create_member_task', description: 'Create a task for a team member', requiredParams: ['member_id', 'title'], apiEndpoint: '/api/v1/team-members/{id}/tasks', httpMethod: 'POST' },
          { name: 'update_member_task', description: 'Update a task for a team member', requiredParams: ['member_id', 'task_id'], apiEndpoint: '/api/v1/team-members/{id}/tasks/{tid}', httpMethod: 'PATCH' },
          { name: 'delete_member_task', description: 'Delete a task for a team member', requiredParams: ['member_id', 'task_id'], apiEndpoint: '/api/v1/team-members/{id}/tasks/{tid}', httpMethod: 'DELETE' },
          { name: 'get_timesheets', description: 'Get timesheet entries for a member', requiredParams: ['member_id'], apiEndpoint: '/api/v1/team-members/{id}/timesheets', httpMethod: 'GET' },
          { name: 'create_timesheet_entry', description: 'Create a timesheet entry', requiredParams: ['member_id', 'date', 'hours'], apiEndpoint: '/api/v1/team-members/{id}/timesheets', httpMethod: 'POST' },
          { name: 'update_timesheet_entry', description: 'Update a timesheet entry', requiredParams: ['member_id', 'entry_id'], apiEndpoint: '/api/v1/team-members/{id}/timesheets/{eid}', httpMethod: 'PUT' },
          { name: 'delete_timesheet_entry', description: 'Delete a timesheet entry', requiredParams: ['member_id', 'entry_id'], apiEndpoint: '/api/v1/team-members/{id}/timesheets/{eid}', httpMethod: 'DELETE' },
          { name: 'export_timesheet', description: 'Export timesheet for a member', requiredParams: ['member_id'], apiEndpoint: '/api/v1/team-members/{id}/timesheets/export', httpMethod: 'GET' },
          { name: 'get_timesheet_config', description: 'Get timesheet configuration', requiredParams: ['member_id'], apiEndpoint: '/api/v1/team-members/{id}/timesheet-config', httpMethod: 'GET' },
          { name: 'update_timesheet_config', description: 'Update timesheet configuration', requiredParams: ['member_id', 'config'], apiEndpoint: '/api/v1/team-members/{id}/timesheet-config', httpMethod: 'PUT' },
        ],
      },
      {
        name: 'Time',
        icon: 'schedule',
        toolCount: 7,
        tools: [
          { name: 'list_leave_records', description: 'List leave records', requiredParams: [], apiEndpoint: '/api/v1/leave-records', httpMethod: 'GET' },
          { name: 'create_leave_record', description: 'Record leave for a team member', requiredParams: ['team_member_id', 'start_date', 'end_date', 'type', 'days_count'], apiEndpoint: '/api/v1/leave-records', httpMethod: 'POST' },
          { name: 'update_leave_record', description: 'Update a leave record', requiredParams: ['leave_id'], apiEndpoint: '/api/v1/leave-records/{id}', httpMethod: 'PUT' },
          { name: 'delete_leave_record', description: 'Delete a leave record', requiredParams: ['leave_id'], apiEndpoint: '/api/v1/leave-records/{id}', httpMethod: 'DELETE' },
          { name: 'import_leave_records', description: 'Import leave records from uploaded data', requiredParams: ['records'], apiEndpoint: '/api/v1/leave-records/import', httpMethod: 'POST' },
          { name: 'fetch_leave_preview', description: 'Preview leave data from external source', requiredParams: [], apiEndpoint: '/api/v1/leave-records/fetch-preview', httpMethod: 'POST' },
          { name: 'fetch_leave_records', description: 'Fetch and import leave records', requiredParams: [], apiEndpoint: '/api/v1/leave-records/fetch', httpMethod: 'POST' },
        ],
      },
      {
        name: 'Discussion',
        icon: 'forum',
        toolCount: 8,
        tools: [
          { name: 'list_discussion_points', description: 'List all discussion points', requiredParams: [], apiEndpoint: '/api/v1/discussion-points', httpMethod: 'GET' },
          { name: 'create_discussion_point', description: 'Create a discussion point', requiredParams: ['title'], apiEndpoint: '/api/v1/discussion-points', httpMethod: 'POST' },
          { name: 'update_discussion_point', description: 'Update a discussion point', requiredParams: ['discussion_id'], apiEndpoint: '/api/v1/discussion-points/{id}', httpMethod: 'PUT' },
          { name: 'delete_discussion_point', description: 'Delete a discussion point', requiredParams: ['discussion_id'], apiEndpoint: '/api/v1/discussion-points/{id}', httpMethod: 'DELETE' },
          { name: 'get_discussion_tasks', description: 'Get tasks for a discussion point', requiredParams: ['discussion_id'], apiEndpoint: '/api/v1/discussion-points/{id}/tasks', httpMethod: 'GET' },
          { name: 'create_discussion_task', description: 'Create a task for a discussion point', requiredParams: ['discussion_id', 'title'], apiEndpoint: '/api/v1/discussion-points/{id}/tasks', httpMethod: 'POST' },
          { name: 'update_discussion_task', description: 'Update a discussion task', requiredParams: ['discussion_id', 'task_id'], apiEndpoint: '/api/v1/discussion-points/{id}/tasks/{tid}', httpMethod: 'PUT' },
          { name: 'delete_discussion_task', description: 'Delete a discussion task', requiredParams: ['discussion_id', 'task_id'], apiEndpoint: '/api/v1/discussion-points/{id}/tasks/{tid}', httpMethod: 'DELETE' },
          { name: 'toggle_discussion_task', description: 'Toggle completion status of a discussion task', requiredParams: ['discussion_id', 'task_id'], apiEndpoint: '/api/v1/discussion-points/{id}/tasks/{tid}/toggle', httpMethod: 'POST' },
        ],
      },
      {
        name: 'Gamification',
        icon: 'emoji_events',
        toolCount: 27,
        tools: [
          { name: 'get_leaderboard', description: 'Get the team leaderboard', requiredParams: [], apiEndpoint: '/api/v1/leaderboard', httpMethod: 'GET' },
          { name: 'get_leaderboard_member_stats', description: 'Get leaderboard stats for a member', requiredParams: ['member_id'], apiEndpoint: '/api/v1/leaderboard/member/{id}', httpMethod: 'GET' },
          { name: 'get_leaderboard_member_history', description: 'Get point history for a member', requiredParams: ['member_id'], apiEndpoint: '/api/v1/leaderboard/member/{id}/history', httpMethod: 'GET' },
          { name: 'award_points', description: 'Award leaderboard points', requiredParams: ['team_member_id', 'points', 'reason'], apiEndpoint: '/api/v1/leaderboard/award', httpMethod: 'POST' },
          { name: 'revoke_points', description: 'Revoke a point award', requiredParams: ['award_id'], apiEndpoint: '/api/v1/leaderboard/award/{id}', httpMethod: 'DELETE' },
          { name: 'list_achievements', description: 'List all available achievements', requiredParams: [], apiEndpoint: '/api/v1/achievements', httpMethod: 'GET' },
          { name: 'get_member_achievements', description: 'Get achievements for a member', requiredParams: ['member_id'], apiEndpoint: '/api/v1/achievements/member/{id}', httpMethod: 'GET' },
          { name: 'award_achievement', description: 'Award an achievement to a member', requiredParams: ['member_id', 'achievement_type'], apiEndpoint: '/api/v1/achievements/award', httpMethod: 'POST' },
          { name: 'revoke_achievement', description: 'Revoke an achievement', requiredParams: ['achievement_id'], apiEndpoint: '/api/v1/achievements/{id}', httpMethod: 'DELETE' },
          { name: 'get_win_of_week_current', description: 'Get the current win of the week', requiredParams: [], apiEndpoint: '/api/v1/win-of-the-week/current', httpMethod: 'GET' },
          { name: 'create_win_week_nomination', description: 'Create a win of the week nomination', requiredParams: ['member_id', 'description'], apiEndpoint: '/api/v1/win-of-the-week/nominations', httpMethod: 'POST' },
          { name: 'vote_win_week', description: 'Vote for a win of the week nomination', requiredParams: ['nomination_id'], apiEndpoint: '/api/v1/win-of-the-week/nominations/{id}/vote', httpMethod: 'POST' },
          { name: 'remove_vote_win_week', description: 'Remove vote from a win of the week', requiredParams: ['nomination_id'], apiEndpoint: '/api/v1/win-of-the-week/nominations/{id}/vote', httpMethod: 'DELETE' },
          { name: 'close_win_week', description: 'Close the current win of the week', requiredParams: [], apiEndpoint: '/api/v1/win-of-the-week/close', httpMethod: 'POST' },
          { name: 'open_next_win_week', description: 'Open the next win of the week', requiredParams: [], apiEndpoint: '/api/v1/win-of-the-week/open-next', httpMethod: 'POST' },
          { name: 'open_win_week_voting', description: 'Open voting for win of the week', requiredParams: [], apiEndpoint: '/api/v1/win-of-the-week/open-voting', httpMethod: 'POST' },
          { name: 'get_win_week_history', description: 'Get win of the week history', requiredParams: [], apiEndpoint: '/api/v1/win-of-the-week/history', httpMethod: 'GET' },
          { name: 'get_win_week_detail', description: 'Get detail for a specific win of the week', requiredParams: ['week_id'], apiEndpoint: '/api/v1/win-of-the-week/weeks/{id}', httpMethod: 'GET' },
          { name: 'get_win_of_month_current', description: 'Get the current win of the month', requiredParams: [], apiEndpoint: '/api/v1/win-of-the-month/current', httpMethod: 'GET' },
          { name: 'get_win_of_month_history', description: 'Get win of the month history', requiredParams: [], apiEndpoint: '/api/v1/win-of-the-month/history', httpMethod: 'GET' },
          { name: 'vote_win_month', description: 'Vote for a win of the month nomination', requiredParams: ['nomination_id'], apiEndpoint: '/api/v1/win-of-the-month/nominations/{id}/vote', httpMethod: 'POST' },
          { name: 'remove_vote_win_month', description: 'Remove vote from a win of the month', requiredParams: ['nomination_id'], apiEndpoint: '/api/v1/win-of-the-month/nominations/{id}/vote', httpMethod: 'DELETE' },
          { name: 'close_win_month', description: 'Close the current win of the month', requiredParams: [], apiEndpoint: '/api/v1/win-of-the-month/close', httpMethod: 'POST' },
          { name: 'generate_win_month', description: 'Generate win of the month from closed weeks', requiredParams: [], apiEndpoint: '/api/v1/win-of-the-month/generate', httpMethod: 'POST' },
          { name: 'open_win_month', description: 'Open voting for win of the month', requiredParams: [], apiEndpoint: '/api/v1/win-of-the-month/open', httpMethod: 'POST' },
          { name: 'list_wheels', description: 'List all wheels', requiredParams: [], apiEndpoint: '/api/v1/wheels', httpMethod: 'GET' },
          { name: 'create_wheel', description: 'Create a new wheel', requiredParams: ['name'], apiEndpoint: '/api/v1/wheels', httpMethod: 'POST' },
          { name: 'delete_wheel', description: 'Delete a wheel', requiredParams: ['wheel_id'], apiEndpoint: '/api/v1/wheels/{id}', httpMethod: 'DELETE' },
          { name: 'add_wheel_participant', description: 'Add a participant to a wheel', requiredParams: ['wheel_id', 'member_id'], apiEndpoint: '/api/v1/wheels/{id}/participants/{mid}', httpMethod: 'POST' },
          { name: 'remove_wheel_participant', description: 'Remove a participant from a wheel', requiredParams: ['wheel_id', 'member_id'], apiEndpoint: '/api/v1/wheels/{id}/participants/{mid}', httpMethod: 'DELETE' },
        ],
      },
      {
        name: 'System',
        icon: 'settings',
        toolCount: 9,
        tools: [
          { name: 'get_sprint_dashboard', description: 'Get the full sprint dashboard', requiredParams: ['sprint_id'], apiEndpoint: '/api/v1/dashboard/sprint/{id}', httpMethod: 'GET' },
          { name: 'get_sprint_summary', description: 'Get a high-level summary for a sprint', requiredParams: ['sprint_id'], apiEndpoint: '/api/v1/dashboard/sprint/{id}/summary', httpMethod: 'GET' },
          { name: 'get_sprint_blockers', description: 'List all blocked work items for a sprint', requiredParams: ['sprint_id'], apiEndpoint: '/api/v1/dashboard/sprint/{id}/blockers', httpMethod: 'GET' },
          { name: 'get_leave_summary', description: 'Get the leave summary for a sprint', requiredParams: ['sprint_id'], apiEndpoint: '/api/v1/dashboard/sprint/{id}/leave-summary', httpMethod: 'GET' },
          { name: 'export_pptx', description: 'Export a PowerPoint presentation', requiredParams: [], apiEndpoint: '/api/v1/export/pptx', httpMethod: 'POST' },
          { name: 'get_progress', description: 'Get all progress data', requiredParams: [], apiEndpoint: '/api/v1/progress', httpMethod: 'GET' },
          { name: 'get_comments', description: 'Get comments for an entity', requiredParams: ['entity_type', 'entity_id'], apiEndpoint: '/api/v1/comments/{type}/{id}', httpMethod: 'GET' },
          { name: 'create_comment', description: 'Create a comment on an entity', requiredParams: ['entity_type', 'entity_id', 'content'], apiEndpoint: '/api/v1/comments', httpMethod: 'POST' },
          { name: 'delete_comment', description: 'Delete a comment', requiredParams: ['comment_id'], apiEndpoint: '/api/v1/comments/{id}', httpMethod: 'DELETE' },
          { name: 'get_auth_mode', description: 'Get the current authentication mode', requiredParams: [], apiEndpoint: '/api/auth-mode', httpMethod: 'GET' },
          { name: 'exchange_auth_code', description: 'Exchange an auth code for tokens', requiredParams: ['code'], apiEndpoint: '/api/auth/exchange', httpMethod: 'POST' },
          { name: 'get_unlinked_users', description: 'Get users not linked to team members', requiredParams: [], apiEndpoint: '/api/users/unlinked', httpMethod: 'GET' },
          { name: 'link_user', description: 'Link a user to a team member', requiredParams: ['user_id', 'member_id'], apiEndpoint: '/api/users/link', httpMethod: 'POST' },
          { name: 'toggle_user_active', description: 'Toggle active status of a user', requiredParams: ['user_id'], apiEndpoint: '/api/users/{id}/toggle', httpMethod: 'PATCH' },
          { name: 'get_sprint_members', description: 'Get all members assigned to a sprint', requiredParams: ['sprint_id'], apiEndpoint: '/api/v1/sprint-members/sprint/{id}', httpMethod: 'GET' },
          { name: 'update_sprint_member_notes', description: 'Update notes for a sprint member', requiredParams: ['sprint_member_id', 'notes'], apiEndpoint: '/api/v1/sprint-members/{id}/notes', httpMethod: 'PATCH' },
          { name: 'update_sprint_member_capacity', description: 'Update capacity for a sprint member', requiredParams: ['sprint_member_id', 'capacity'], apiEndpoint: '/api/v1/sprint-members/{id}/capacity', httpMethod: 'PATCH' },
        ],
      },
    ];
  }

  getFeatureCards(): FeatureCard[] {
    return [
      { domain: 'PIs', icon: 'account_tree', color: '#42a5f5', route: '/sprints', tags: ['Program Increments', 'Sprint grouping'], description: 'Program Increments grouping sprints' },
      { domain: 'Sprints', icon: 'directions_run', color: '#42a5f5', route: '/sprints', tags: ['Planning', 'Tracking', 'Retro'], description: 'Sprint planning and tracking' },
      { domain: 'Team Members', icon: 'people', color: '#66bb6a', route: '/team', tags: ['CRUD', 'Skills', 'Notes'], description: 'Team member management' },
      { domain: 'Squads', icon: 'groups', color: '#66bb6a', route: '/team', tags: ['Organization', 'Multi-membership'], description: 'Squad organization' },
      { domain: 'Work Items', icon: 'task_alt', color: '#42a5f5', route: '/sprints', tags: ['Tasks', 'Bugs', 'QA', 'Dev'], description: 'Tasks, bugs, analysis, dev, QA' },
      { domain: 'Meetings', icon: 'event', color: '#ab47bc', route: '/meetings', tags: ['Series', 'Sessions', 'Availability'], description: 'Meeting series, sessions, availability' },
      { domain: 'Discussion', icon: 'forum', color: '#7e57c2', route: '/discussion', tags: ['Points', 'Tasks', 'Toggle'], description: 'Discussion points and tasks' },
      { domain: 'Timesheets', icon: 'schedule', color: '#26a69a', route: '/team', tags: ['Tracking', 'Export', 'Config'], description: 'Time tracking and export' },
      { domain: 'Leave', icon: 'event_busy', color: '#26a69a', route: '/leave', tags: ['Records', 'Import', 'Types'], description: 'Leave records management' },
      { domain: 'Win Week/Month', icon: 'emoji_events', color: '#ffa726', route: '/fun', tags: ['Nominations', 'Voting'], description: 'Win of the week and month' },
      { domain: 'Leaderboard', icon: 'leaderboard', color: '#ffa726', route: '/fun/leaderboard', tags: ['Points', 'Rankings', 'History'], description: 'Points rankings and history' },
      { domain: 'Achievements', icon: 'trophy', color: '#ffa726', route: '/fun', tags: ['Awards', 'Types'], description: 'Achievement awards' },
      { domain: 'Wheels', icon: 'casino', color: '#ffa726', route: '/fun/wheel', tags: ['Random', 'Participants'], description: 'Random assignment wheels' },
      { domain: 'Export', icon: 'download', color: '#78909c', route: '/export', tags: ['PPTX', 'Presentation'], description: 'PowerPoint export' },
      { domain: 'Progress', icon: 'show_chart', color: '#78909c', route: '/progress', tags: ['Timeline', 'PI view'], description: 'Progress tracking timeline' },
      { domain: 'Comments', icon: 'comment', color: '#78909c', route: '/dashboard', tags: ['Any entity', 'Threaded'], description: 'Comments on any entity' },
      { domain: 'Session Types', icon: 'settings', color: '#78909c', route: '/session-types', tags: ['Configurable', 'Duration'], description: 'Session type definitions' },
      { domain: 'Auth', icon: 'lock', color: '#78909c', route: '/profile', tags: ['OAuth', 'User linking'], description: 'API keys, user linking' },
    ];
  }
}
