FROM node:22-alpine
ENV NODE_OPTIONS="--max-old-space-size=4096"
WORKDIR /app
COPY package*.json ./
RUN npm install --legacy-peer-deps --prefer-offline
COPY . .
EXPOSE 6006
CMD ["npm", "run", "storybook"]
